# Generated by Django 3.2.8 on 2021-11-24 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.TextField(max_length=150)),
                ('created', models.DateTimeField()),
                ('completed', models.BooleanField()),
            ],
        ),
    ]
